name: Build & Release Windows App

on:
  push:
    tags:
      - "v*"   # nur bei Tags wie v1.0.0 ausf체hren

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore DartTournamentPlaner.sln

      - name: Build Release
        run: msbuild DartTournamentPlaner.sln /p:Configuration=Release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp
          path: |
            **\bin\Release\**
  
  release:
    needs: build
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: MyApp
          path: ./release

      - name: Create ZIP package
        shell: pwsh
        run: |
          $tag = "${{ github.ref_name }}"
          $zipName = "DartTournamentPlaner-Release-$tag.zip"
          echo "Creating $zipName..."

          # Ordner auf den spezifischen net9.0-windows Build setzen
          $buildDir = "release/DartTournamentPlaner/bin/Release/net9.0-windows"

          if (-Not (Test-Path $buildDir)) {
            echo "Build directory not found: $buildDir"
            exit 1
          }

          # Alle Dateien in diesem Ordner ins ZIP
          $items = Get-ChildItem -Path $buildDir -File
          Compress-Archive -Path $items.FullName -DestinationPath $zipName -Force

          echo "ZIP_PATH=$zipName" >> $env:GITHUB_ENV

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Build Installer
        shell: pwsh
        run: |
          $tag = "${{ github.ref_name }}"
          # Version an Inno Setup 체bergeben
          iscc.exe /dMyAppVersion=$tag installer.iss
          $installer = Get-ChildItem -Path Output -Filter "*.exe" | Select-Object -First 1
          echo "INSTALLER_PATH=$($installer.FullName)" >> $env:GITHUB_ENV

      - name: Extract changelog section
        id: changelog
        shell: pwsh
        run: |
          $tag = "${{ github.ref_name }}"
          $content = Get-Content CHANGELOG.md
          
          # Zeile mit "## vX.Y.Z" finden
          $start = ($content | Select-String "^## $tag").LineNumber
          if (-not $start) { 
            echo "No changelog entry found for $tag" 
            exit 1 
          }
          
          # Alles ab dem gefundenen Tag nehmen
          $rest = $content[($start-1)..($content.Length - 1)]
          
          # N채chsten "## v..." Header suchen (체berspringt die erste Zeile)
          $nextHeader = ($rest | Select-String "^## v[0-9]" | Select-Object -Skip 1 | Select-Object -First 1).LineNumber
          
          if ($nextHeader) {
            $section = $rest[0..($nextHeader-2)]
          } else {
            $section = $rest
          }
          
          $sectionText = $section -join "`n"
          echo "content<<EOF" >> $env:GITHUB_OUTPUT
          echo "$sectionText" >> $env:GITHUB_OUTPUT
          echo "EOF" >> $env:GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.content }}
          files: |
            ${{ env.ZIP_PATH }}
            ${{ env.INSTALLER_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
